version: "3.9"
services:
  local-db:
    image: api-starter-db
    env_file: ./local.env
    ports:
      - "2000:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U api-user -d api-starter"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
